name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install deps
      run: python -m pip install -r requirements.txt
    - name: Lint ruff
      run: python -m ruff check ace_workspace/main.py
    - name: Mypy
      run: python -m mypy ace_workspace/main.py
    - name: Bandit security
      run: python -m bandit -r ace_workspace/main.py
    - name: Pytest
      run: python -m pytest -q
